### ISSUE TITLE
Mind removing my codes brotha 😅

### ISSUE THREAD

**Issue by CR072** [privt00/tfc-plex#5]
These files are copied from HolaClient,
https://github.com/privt00/tfc-plex/blob/main/api/purge.js
https://github.com/privt00/tfc-plex/blob/main/api/landing.js
https://github.com/privt00/tfc-plex/blob/main/sec/antipterovm.js
https://github.com/privt00/tfc-plex/blob/main/log.js
https://github.com/privt00/tfc-plex/blob/main/themes/default/index.ejs

Landing page too 

HolaClient is a FOSS software licensed under Apache v2, It provides more freedom to contributors/developers in copyright grounds, However you still have to obey the license's ToS and T&C. You should give credits to the original authors and the project, I want you to take down the codes from every platform Tfc-plex is hosted on. We hope this won't happen again as this is not the first time we're asking you to remove these codes.

Eagerly waiting for your anticipated reply & action.
CR072

Personal advice:
AI won't make your code work better, but your own brain will.

**Comment by privt00** [comment]
yeah ik. demon said i can keep https://github.com/privt00/tfc-plex/blob/main/api/landing.js
